version: '3.7'

services:
  realworld:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=${ENV}
      - JWT_KEY=${JWT_KEY}
      - ${PREFIX}_DB_USERNAME=${MYSQL_USER:-root}
      - ${PREFIX}_DB_PASSWORD=${MYSQL_PASSWORD:-mysecretpassword}
      - ${PREFIX}_DB_NAME=realworld-db
      - ${PREFIX}_DB_HOSTNAME=mysql
      - ${PREFIX}_DB_DIALECT=mysql
      - ${PREFIX}_DB_LOGGGIN=true
    ports:
      - "${PORT:-3001}:3001"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: realworld-app
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-mysecretpassword}
      - MYSQL_DATABASE=realworld-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: