name: deploy_production
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/github-pages.yml'
jobs:
  checkout:
    runs-on: realworld-runner
    steps:
      - uses: actions/checkout@v4
  deploy:
    runs-on: realworld-runner
    needs: checkout
    steps:
      - name: deploy
        env:
          ENV: production
          PREFIX: PROD
          JWT_KEY: ${{ secrets.JWT_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PORT: 3001
        run: |
          docker compose --project-name realworld-${ENV} build
          docker compose --project-name realworld-${ENV} up -d
          docker image prune -f